db:
  image: mysql:5.7.25
  container_name: sadok_learning_db
  ports:
    - 3313:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: sadok_learning_db
  command:
    ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
